### ISSUE TITLE
Injection code execution

### ISSUE THREAD

**Issue by iinQ1337** [hackirby/discord-injection#2]
When restarting Discord, the code doesn't execute. It feels like the executeJS function is not working, and the user is not logged out of the account

536 line

**Comment by hackirby** [comment]
To enable the logout function, make sure to create a folder titled `initiation` in the `discord_desktop_core` directory, as indicated in the code. Also, verify that you are using a valid webhook to avoid any errors and ensure the proper execution of the executeJS function.

If you encounter any issues, feel free to reach out, and I'll gladly assist you further.
