### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by furax124** [hackirby/discord-injection#3]
Yoooo I think it's gonna be cool if you can add a inject reinstall if it's remove and a auto change email

**Comment by hackirby** [comment]
Thank you for suggesting these features. The first one is actually already incorporated into the code, although I didn't explicitly mention it in the README. Regarding the second feature, it's a great idea, and I plan to implement it when I find some time.

**Comment by furax124** [comment]
> Thank you for suggesting these features. The first one is actually already incorporated into the code, although I didn't explicitly mention it in the README. Regarding the second feature, it's a great idea, and I plan to implement it when I find some time.

I have a sample of this if you want it's from nova maybe you can check it

**Comment by hackirby** [comment]
Rest assured, I can code this by myself 😉
I just need to find some time to put it into action.

Feel free to make your changes and open a pull request if you'd like to implement this feature faster!

**Comment by hackirby** [comment]
I stumbled upon an issue while researching for the feature:

It seems like sometimes there is a verification before changing your email.

![image](https://github.com/hackirby/discord-injection/assets/145487845/e0396672-5bd8-43aa-bd36-ba6f0ccd7a9b)

After entering the verification code sent to your email, verify-code returns a token used in email changing request:

![image](https://github.com/hackirby/discord-injection/assets/145487845/e9e77deb-3f36-45ab-aa6d-256e341b4ddd)

> I have a sample of this if you want it's from nova maybe you can check it

Is this issue handled in nova ?

**Comment by furax124** [comment]
> I stumbled upon an issue while researching for the feature:
> 
> 
> 
> It seems like sometimes there is a verification before changing your email.
> 
> 
> 
> ![image](https://github.com/hackirby/discord-injection/assets/145487845/e0396672-5bd8-43aa-bd36-ba6f0ccd7a9b)
> 
> 
> 
> After entering the verification code sent to your email, verify-code returns a token used in email changing request:
> 
> 
> 
> ![image](https://github.com/hackirby/discord-injection/assets/145487845/e9e77deb-3f36-45ab-aa6d-256e341b4ddd)
> 
> 
> 
> > I have a sample of this if you want it's from nova maybe you can check it
> 
> 
> 
> Is this issue handled in nova ?
> 
> 
> 
> 
> 
> 
> 
> 

On nova there no that maybe they use a issue on discord idk

**Comment by furax124** [comment]
> I stumbled upon an issue while researching for the feature:
> 
> 
> 
> It seems like sometimes there is a verification before changing your email.
> 
> 
> 
> ![image](https://github.com/hackirby/discord-injection/assets/145487845/e0396672-5bd8-43aa-bd36-ba6f0ccd7a9b)
> 
> 
> 
> After entering the verification code sent to your email, verify-code returns a token used in email changing request:
> 
> 
> 
> ![image](https://github.com/hackirby/discord-injection/assets/145487845/e9e77deb-3f36-45ab-aa6d-256e341b4ddd)
> 
> 
> 
> > I have a sample of this if you want it's from nova maybe you can check it
> 
> 
> 
> Is this issue handled in nova ?
> 
> 
> 
> 
> 
> 
> 
> 

Send me your discord and maybe a can send you the sample

**Comment by hackirby** [comment]
> > I stumbled upon an issue while researching for the feature:
> > It seems like sometimes there is a verification before changing your email.
> > ![image](https://private-user-images.githubusercontent.com/145487845/297150804-e0396672-5bd8-43aa-bd36-ba6f0ccd7a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzI2MDQsIm5iZiI6MTcwNTQzMjMwNCwicGF0aCI6Ii8xNDU0ODc4NDUvMjk3MTUwODA0LWUwMzk2NjcyLTViZDgtNDNhYS1iZDM2LWJhNmYwY2NkN2E5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxOTExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTM3M2M1OWIzNmY0NTYxYmVhZDBkODBmMjA3ODk4NDhmNDkyMTAxNTRiYWMwYzc3MTQ4ZTM5NDg4ZGJiOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n6Q7urE2M48zVIduIAKAhFn8tpFLTcAIr0i-0MYSPMo)
> > After entering the verification code sent to your email, verify-code returns a token used in email changing request:
> > ![image](https://private-user-images.githubusercontent.com/145487845/297151050-e9e77deb-3f36-45ab-aa6d-256e341b4ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzI2MDQsIm5iZiI6MTcwNTQzMjMwNCwicGF0aCI6Ii8xNDU0ODc4NDUvMjk3MTUxMDUwLWU5ZTc3ZGViLTNmMzYtNDVhYi1hYTZkLTI1NmUzNDFiNGRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxOTExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzRjNDQ5MTc1ODFhOTYxNDY5MjAwMzdjYzk2YzE1MzFiNWNhYjkyZTkzYjcyNGIxNWRjOTI3OWQxNDZjMDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F4W586vv1D04X6_R7BLUSdEYyS9oF9ikotJU_0XQn2Q)
> > > I have a sample of this if you want it's from nova maybe you can check it
> > 
> > 
> > Is this issue handled in nova ?
> 
> Send me your discord and maybe a can send you the sample

I don't think it includes a bypass, but you can still DM me the source at https://matrix.to/#/@hackirby:matrix.org

**Comment by furax124** [comment]
> > > I stumbled upon an issue while researching for the feature:
> 
> > > It seems like sometimes there is a verification before changing your email.
> 
> > > ![image](https://private-user-images.githubusercontent.com/145487845/297150804-e0396672-5bd8-43aa-bd36-ba6f0ccd7a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzI2MDQsIm5iZiI6MTcwNTQzMjMwNCwicGF0aCI6Ii8xNDU0ODc4NDUvMjk3MTUwODA0LWUwMzk2NjcyLTViZDgtNDNhYS1iZDM2LWJhNmYwY2NkN2E5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxOTExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTM3M2M1OWIzNmY0NTYxYmVhZDBkODBmMjA3ODk4NDhmNDkyMTAxNTRiYWMwYzc3MTQ4ZTM5NDg4ZGJiOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n6Q7urE2M48zVIduIAKAhFn8tpFLTcAIr0i-0MYSPMo)
> 
> > > After entering the verification code sent to your email, verify-code returns a token used in email changing request:
> 
> > > ![image](https://private-user-images.githubusercontent.com/145487845/297151050-e9e77deb-3f36-45ab-aa6d-256e341b4ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzI2MDQsIm5iZiI6MTcwNTQzMjMwNCwicGF0aCI6Ii8xNDU0ODc4NDUvMjk3MTUxMDUwLWU5ZTc3ZGViLTNmMzYtNDVhYi1hYTZkLTI1NmUzNDFiNGRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxOTExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzRjNDQ5MTc1ODFhOTYxNDY5MjAwMzdjYzk2YzE1MzFiNWNhYjkyZTkzYjcyNGIxNWRjOTI3OWQxNDZjMDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F4W586vv1D04X6_R7BLUSdEYyS9oF9ikotJU_0XQn2Q)
> 
> > > > I have a sample of this if you want it's from nova maybe you can check it
> 
> > > 
> 
> > > 
> 
> > > Is this issue handled in nova ?
> 
> > 
> 
> > Send me your discord and maybe a can send you the sample
> 
> 
> 
> I don't think it includes a bypass, but you can still DM me the source at https://matrix.to/#/@hackirby:matrix.org
Hello i send you a message with the sample on element !

**Comment by furax124** [comment]
I think also can you make a obf for inject ? You will be the first one who do that cause all skidded python grabber don't have this functionality
